### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by u17194907425** [thanksmister/voice-panel-android#10]
Hey Mister, is there any roadmap you might be willing to share?
The application is looking very promising and since I'm currently out of options with my hass.io installation when it comes to connecting mic, I'm looking at VoicePanel as a viable option to be the **main** thing to host voice control. Hell, maybe I'll even make it to compile it myself in order to inject the snips config I need :)

The questions though, how do you see this app into the future?

- combining it into one app with **Home Panel**?
- enabling the user to upload custom **assistant.zip**?
- maybe adding some sound feedback when the wake-word was recognized?

Thanks!

**Comment by thanksmister** [comment]
1) What is Home Panel?  

2) You can add your own assistant by downloading the source code and compiling it with the application.  I have not plans to add a way to download and update the assistant within the application at this time.   

Alternatively, you can request we add additional apps to the assistant if they are available from the Snips console.  I have created a few apps just for this assistent because I didn't find a great integration with Home Assistant. 

3) There is already an animation when the wake word is heard on the main screen, are you not seeing that?

I don't know what the future holds for the application other than possibly adding more functionality to the assistant by adding more apps when generating the zip file.   A lot depends what is the future of Snips as a company.

**Comment by u17194907425** [comment]
1. Mah bad... Wall Panel (https://github.com/thanksmister/wallpanel-android). My apologies. Feels embarrassing.
1. Gotcha, thank you!
1. Yep, I see it. I was thinking about a use-where where the device itself is hidden. E.g. I place it somewhere on a high shelf and use a microphone only without seeing the screen.

**Comment by thanksmister** [comment]
I don't have any plans at this time to integrate the two applications, WallPanel and VoicePanel.  Though I think I know for you, you want your home assistant dashboard to be controlled by voice, so something like WallPanel with voice control would be ideal.   

I think WallPanel has about 5000 users, this app maybe 400.  So the demand to make another app, a voice control web dashboard, might be minimal. 

I think you want sound feedback right?  That's possible, we can add an option for using the device sounds, though you could also add some simple voice feedback, like "yes" or "how can I help" using the built-in voice.

**Comment by u17194907425** [comment]
The 1st one was just out curiosity. When I saw the both apps I felt like they are close to each other and a lot of code can be re-used. Got your point about the plans. Thanks.

_I think you want sound feedback right?_ - Correct. A beep or a TTS "yes". Should I go ahead and submit this as a separate issue while closing this one?

**Comment by thanksmister** [comment]
Yeah, you can submit an issue as feature and we can add it to the road map.  Also let me know of any Snips apps that you think would be a good addition to the assistant.
